<?php

function statepoll_menu() {
    $items['statepoll-form'] = array(
        'title' => 'State Ice Cream Poll',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('statepoll_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    $items['statepoll-success'] = array(
        'title' => 'Survey Success',
        'page callback' => 'statepoll_results',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );

    return $items;

}

function statepoll_form() {
    $form['ice_cream'] = array(
        '#title' => 'Ice Cream',
        '#type' => 'textfield',
        '#description' => t('Enter your favorite ice cream.'),
        '#element_validate' => array('element_validate_statepoll_word'),
        '#required' => TRUE,
    );
    $form['state'] = array(
        '#title' => 'State',
        '#type' => 'textfield',
        '#description' => t('Enter your home state.'),
        '#element_validate' => array('element_validate_statepoll_word', 'element_validate_statepoll_state'),
        '#required' => TRUE,
    );
    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Submit',
    );

    return $form;
}

function statepoll_form_submit($form, &$form_state) {
    $icecream = $form_state['values']['ice_cream'];
    $state = $form_state['values']['state'];

    $_SESSION['statepoll_input'] = [$icecream, $state];

    $form_state['redirect'] = "statepoll-success";
}

function statepoll_results() {
    $input = $_SESSION['statepoll_input'];
    return "<b>Ice cream:</b> $input[0] <b>State:</b> $input[1]";
}


//Validation
function element_validate_statepoll_word($element) {
    if(preg_match('/[^a-zA-Z ]/', $element['#value'])) {
        form_error($element, t('Only letters and spaces are accepted.'));
    }
}

function element_validate_statepoll_state($element) {
    $valid_states = array(
        'AL', 'ALABAMA',
        'AK', 'ALASKA',
        'AS', 'AMERICAN SAMOA',
        'AZ', 'ARIZONA',
        'AR', 'ARKANSAS',
        'CA', 'CALIFORNIA',
        'CO', 'COLORADO',
        'CT', 'CONNECTICUT',
        'DE', 'DELAWARE',
        'DC', 'DISTRICT OF COLUMBIA',
        'FM', 'FEDERATED STATES OF MICRONESIA',
        'FL', 'FLORIDA',
        'GA', 'GEORGIA',
        'GU', 'GUAM GU',
        'HI', 'HAWAII',
        'ID', 'IDAHO',
        'IL', 'ILLINOIS',
        'IN', 'INDIANA',
        'IA', 'IOWA',
        'KS', 'KANSAS',
        'KY', 'KENTUCKY',
        'LA', 'LOUISIANA',
        'ME', 'MAINE',
        'MH', 'MARSHALL ISLANDS',
        'MD', 'MARYLAND',
        'MA', 'MASSACHUSETTS',
        'MI', 'MICHIGAN',
        'MN', 'MINNESOTA',
        'MS', 'MISSISSIPPI',
        'MO', 'MISSOURI',
        'MT', 'MONTANA',
        'NE', 'NEBRASKA',
        'NV', 'NEVADA',
        'NH', 'NEW HAMPSHIRE',
        'NJ', 'NEW JERSEY',
        'NM', 'NEW MEXICO',
        'NY', 'NEW YORK',
        'NC', 'NORTH CAROLINA',
        'ND', 'NORTH DAKOTA',
        'MP', 'NORTHERN MARIANA ISLANDS',
        'OH', 'OHIO',
        'OK', 'OKLAHOMA',
        'OR', 'OREGON',
        'PW', 'PALAU',
        'PA', 'PENNSYLVANIA',
        'PR', 'PUERTO RICO',
        'RI', 'RHODE ISLAND',
        'SC', 'SOUTH CAROLINA',
        'SD', 'SOUTH DAKOTA',
        'TN', 'TENNESSEE',
        'TX', 'TEXAS',
        'UT', 'UTAH',
        'VT', 'VERMONT',
        'VI', 'VIRGIN ISLANDS',
        'VA', 'VIRGINIA',
        'WA', 'WASHINGTON',
        'WV', 'WEST VIRGINIA',
        'WI', 'WISCONSIN',
        'WY', 'WYOMING',
    );

    if (!in_array(strtoupper($element['#value']), $valid_states)) {
        form_error($element, t('Please enter a valid state.'));
    }
}
